# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1057, 796)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("hand_bone_sh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:rgb(31, 31, 31)")
        self.before_button = QtWidgets.QPushButton(Dialog)
        self.before_button.setGeometry(QtCore.QRect(40, 690, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.before_button.setFont(font)
        self.before_button.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(50, 50, 50);\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(194, 194, 194);\n"
"}")
        self.before_button.setObjectName("before_button")
        self.next_button = QtWidgets.QPushButton(Dialog)
        self.next_button.setGeometry(QtCore.QRect(880, 690, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.next_button.setFont(font)
        self.next_button.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(50, 50, 50);\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(194, 194, 194);\n"
"}")
        self.next_button.setObjectName("next_button")
        self.yolo_label_frame = QtWidgets.QGraphicsView(Dialog)
        self.yolo_label_frame.setGeometry(QtCore.QRect(30, 60, 411, 521))
        self.yolo_label_frame.setStyleSheet("background-color : rgb(250, 250, 250)")
        self.yolo_label_frame.setObjectName("yolo_label_frame")
        self.label_change_button = QtWidgets.QPushButton(Dialog)
        self.label_change_button.setGeometry(QtCore.QRect(30, 590, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_change_button.setFont(font)
        self.label_change_button.setStyleSheet("background-color: rgb(107, 107, 107);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(214, 214, 214);\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(194, 194, 194);\n"
"}")
        self.label_change_button.setObjectName("label_change_button")
        self.description_label = QtWidgets.QLabel(Dialog)
        self.description_label.setGeometry(QtCore.QRect(150, 590, 291, 41))
        self.description_label.setStyleSheet("background-color:rgb(52, 52, 52);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(230, 230, 230);\n"
"")
        self.description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label.setObjectName("description_label")
        self.result_button = QtWidgets.QPushButton(Dialog)
        self.result_button.setGeometry(QtCore.QRect(460, 230, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.result_button.setFont(font)
        self.result_button.setStyleSheet("background-color: rgb(209, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(214, 214, 214);\n"
"border-bottom-right-radius: 8px;\n"
"border-bottom-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(194, 194, 194);\n"
"}")
        self.result_button.setObjectName("result_button")
        self.result_frame = QtWidgets.QGraphicsView(Dialog)
        self.result_frame.setGeometry(QtCore.QRect(620, 60, 411, 521))
        self.result_frame.setStyleSheet("background-color : rgb(250, 250, 250);\n"
"\n"
"color: rgb(214, 214, 214);\n"
"border-bottom-right-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"border-top-left-radius: 15px;\n"
"")
        self.result_frame.setObjectName("result_frame")
        self.image2result = QtWidgets.QLabel(Dialog)
        self.image2result.setGeometry(QtCore.QRect(450, 300, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.image2result.setFont(font)
        self.image2result.setStyleSheet("\n"
"color: rgb(255, 0, 0);\n"
"")
        self.image2result.setAlignment(QtCore.Qt.AlignCenter)
        self.image2result.setObjectName("image2result")
        self.TRoBA = QtWidgets.QLabel(Dialog)
        self.TRoBA.setGeometry(QtCore.QRect(640, 80, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.TRoBA.setFont(font)
        self.TRoBA.setStyleSheet("background-color:rgb(52, 52, 52);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(230, 230, 230);\n"
"\n"
"border-bottom-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-top-left-radius: 5px;")
        self.TRoBA.setAlignment(QtCore.Qt.AlignCenter)
        self.TRoBA.setObjectName("TRoBA")
        self.input_name2 = QtWidgets.QLineEdit(Dialog)
        self.input_name2.setGeometry(QtCore.QRect(740, 170, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.input_name2.setFont(font)
        self.input_name2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(124, 124, 124);\n"
"padding-bottom: 7px;")
        self.input_name2.setObjectName("input_name2")
        self.input_Height2 = QtWidgets.QLineEdit(Dialog)
        self.input_Height2.setGeometry(QtCore.QRect(740, 240, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.input_Height2.setFont(font)
        self.input_Height2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(124, 124, 124);\n"
"padding-bottom: 7px;")
        self.input_Height2.setObjectName("input_Height2")
        self.input_gender2 = QtWidgets.QLineEdit(Dialog)
        self.input_gender2.setGeometry(QtCore.QRect(740, 310, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.input_gender2.setFont(font)
        self.input_gender2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 2px solid rgb(35, 35, 35);\n"
"color: rgb(124, 124, 124);\n"
"padding-bottom: 7px;")
        self.input_gender2.setObjectName("input_gender2")
        self.txt_name = QtWidgets.QLabel(Dialog)
        self.txt_name.setGeometry(QtCore.QRect(640, 160, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_name.setFont(font)
        self.txt_name.setStyleSheet("background-color : rgb(250, 250, 250);")
        self.txt_name.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_name.setObjectName("txt_name")
        self.txt_age = QtWidgets.QLabel(Dialog)
        self.txt_age.setGeometry(QtCore.QRect(640, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_age.setFont(font)
        self.txt_age.setStyleSheet("background-color : rgb(250, 250, 250);")
        self.txt_age.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_age.setObjectName("txt_age")
        self.txt_gender = QtWidgets.QLabel(Dialog)
        self.txt_gender.setGeometry(QtCore.QRect(640, 300, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_gender.setFont(font)
        self.txt_gender.setStyleSheet("background-color : rgb(250, 250, 250);")
        self.txt_gender.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_gender.setObjectName("txt_gender")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(790, 380, 71, 71))
        self.label.setStyleSheet("background-color : rgb(255, 255, 255);\n"
"border:none;")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bone Age"))
        self.before_button.setText(_translate("Dialog", "<< BEFORE "))
        self.next_button.setText(_translate("Dialog", "NEXT >>"))
        self.label_change_button.setText(_translate("Dialog", "change_"))
        self.description_label.setText(_translate("Dialog", "YOLO x-ray roi label image"))
        self.result_button.setText(_translate("Dialog", "Result"))
        self.image2result.setText(_translate("Dialog", ">>>"))
        self.TRoBA.setText(_translate("Dialog", "Test Result of Bone Age"))
        self.input_name2.setPlaceholderText(_translate("Dialog", "Name"))
        self.input_Height2.setPlaceholderText(_translate("Dialog", "Age"))
        self.input_gender2.setPlaceholderText(_translate("Dialog", "Gender(F/M)"))
        self.txt_name.setText(_translate("Dialog", "Name"))
        self.txt_age.setText(_translate("Dialog", "Age"))
        self.txt_gender.setText(_translate("Dialog", "Gender"))
        self.label.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/array_icon/arrow.png\" /></p></body></html>"))
import ary_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
